Feature/034 change password
ezteksoftware/painite pull request #15
Opened 2021-06-29 10:53 UTC by halfangel37

I create feature change password and it place inside the user profile , so I created a folder name 'profile' to contain all needed file( components, views, store) , I do it with my experience with register screen, the form also have validated just not like in the design but it familiar with register screen , validate make it easier to deal with the errors, the css of the dashboard created by Thanh Nguy make my form not in the center when responsive with mobile device, so I have to add some css to it. Hope you review it soon.

## Demo 📺
https://www.loom.com/share/9ad4aaa1e8d94ff1aff1ccbe07f860fb

2021-06-29 15:10 UTC, truonghungit commented on src/http-common.js
>    },
Wait for [#044](https://trello.com/c/Lhh5tkRq/46-044-creating-http-clients-using-axios-instances), then we will have an HTTP interceptor that adds authorization token to the header auto

2021-06-29 15:34 UTC, truonghungit requested changes

2021-06-29 15:34 UTC, truonghungit commented on src/profile/store/Profile.js
> +      console.log("state:", state.changePasswordMessage);
Remove console log

2021-06-29 15:34 UTC, truonghungit commented on src/profile/views/Profile.vue
> +    },
```suggestion
    changePassword({currentPassword, newPassword}) {
      this.$store.dispatch("profile/changePassword", {
        oldPassword: currentPassword,
        newPassword,
      });
    },
```

2021-06-29 15:34 UTC, truonghungit commented on src/profile/views/Profile.vue
> +  },
?? Please check [tabs document](https://vuetifyjs.com/en/components/tabs/)

2021-06-29 15:34 UTC, truonghungit commented on src/profile/views/Profile.vue
> +}
active but display `none` ??

2021-06-29 15:34 UTC, truonghungit commented on src/store.js
> +  modules: { register, signin, signout, profile },
```suggestion
  modules: { 
         register,
         signin,
         signout,
         profile,
   },
```

2021-06-29 15:34 UTC, truonghungit commented on src/store.js
> +  modules: { register, signin, signout, profile },
This help us avoid conflict when merging code

2021-06-29 15:34 UTC, truonghungit commented on src/store.js
> +import profile from "./profile/store/Profile";
Rename file `./profile/store/Profile` to `./profile/store/index.js` then we can import `@/profile/store`
```suggestion
import profile from "@/profile/store";
```

2021-06-29 15:34 UTC, truonghungit commented on src/profile/components/ChangePassword.vue
> +</style>
Can you rename this component to `ChangePasswordForm`

2021-06-29 15:34 UTC, truonghungit commented on src/profile/components/ChangePassword.vue
> +
??

2021-06-29 15:44 UTC, truonghungit requested changes

2021-06-29 15:44 UTC, truonghungit commented on src/profile/components/ChangePassword.vue
> +
1. You can move alerts into `Profile.vue ` therefore, you don't need to pass the `changePasswordMessage` props
2. If you want to show  alerts in here, you can rename this props to `errorMessage` for more clear

2021-06-30 06:18 UTC, truonghungit requested changes
Nice work

2021-06-30 06:18 UTC, truonghungit commented on src/profile/store/index.js
> +          }
```suggestion
           const message = error.response.data.errors[0] 
                   ? error.response.data.errors[0].message
                   :  error.response.data.errors.NewPassword[0];
                   
           commit( "SET_PASSWORD_MESSAGE", message);
```

2021-06-30 06:18 UTC, truonghungit commented on src/profile/views/Profile.vue
> +      <v-tab-item v-for="item in items" :key="item">
Nice work

2021-06-30 22:57 UTC, truonghungit approved these changes

2021-07-01 03:12 UTC, luantc13 approved these changes
Great work!

2021-07-01 03:55 UTC, merged