Feature/007 create company screen
ezteksoftware/painite pull request #16
Opened 2021-06-30 03:47 UTC by nguyenvinhduyet

## 007 Create company screen 👋

I have done build UI, handle post API to server.

## Demo 📺

**[Loom Video Demo](https://www.loom.com/share/c07c0956797940c6923455b8773ba469)**

2021-06-30 04:31 UTC, luantc13 reviewed
Lgtm.
Pls wait for Hung's comments.

2021-06-30 04:31 UTC, luantc13 commented on src/Dashboard/components/MainContent.vue
> +      <router-view> </router-view>
No need for the change here. Pls remove the redundant space.

2021-06-30 04:31 UTC, luantc13 commented on src/companies/components/CreateButton.vue
> +<style></style>
I think this button can be more generic, let's called `BaseButton`, and we can do anything with it, not just create.

2021-06-30 04:31 UTC, luantc13 commented on src/companies/components/RegisterCompanyForm.vue
> +          </v-col> -->
Zoombie code, can we remove them?

2021-06-30 04:31 UTC, luantc13 commented on src/companies/components/RegisterCompanyForm.vue
> +</template>-->
Zoombie code.

2021-06-30 04:31 UTC, luantc13 commented on src/companies/components/RegisterCompanyForm.vue
> +      currencyRules: [(v) => !!v || "Currency is required"],
Pls follow the pull request [#10](https://github.com/ezteksoftware/painite/pull/10) to have the reuseable validators.

2021-06-30 04:31 UTC, luantc13 commented on src/companies/store/companies.js
> +  },
Pls remove all console log and alert.

2021-06-30 04:31 UTC, luantc13 commented on src/http-common.js
> +});
We will be no need it after merging the pull request [#17](https://github.com/ezteksoftware/painite/pull/17)

2021-06-30 05:00 UTC, nguyenvinhduyet commented on src/companies/components/RegisterCompanyForm.vue
> +          </v-col> -->
sr, i was removed this

2021-06-30 05:01 UTC, nguyenvinhduyet commented on src/companies/components/RegisterCompanyForm.vue
> +</template>-->
sr, i removed this

2021-06-30 05:01 UTC, nguyenvinhduyet commented on src/companies/components/RegisterCompanyForm.vue
> +      currencyRules: [(v) => !!v || "Currency is required"],
yes sir

2021-06-30 05:02 UTC, nguyenvinhduyet commented on src/companies/store/companies.js
> +  },
yes, i removed that

2021-06-30 05:05 UTC, nguyenvinhduyet commented on src/http-common.js
> +});
oke i got it

2021-06-30 05:28 UTC, nguyenvinhduyet commented on src/companies/components/CreateButton.vue
> +<style></style>
i changed name

2021-06-30 05:28 UTC, nguyenvinhduyet commented on src/companies/components/CreateButton.vue
> +<style></style>
i changed name

2021-06-30 07:00 UTC, truonghungit requested changes
Goodddd Job Duyet

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/BaseButton.vue
> +<style></style>
It is not a BaseButton, because we can reuse it for other buttons like `update`, `edit`, ...
we should change the name of this component to `CreateCompayButton`

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/BaseButton.vue
> +    <v-col>
We probably don't need this line.  `v-col`

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +  props: ["e1"],
what is `e1`.

And we should provide a specific type for prop 
https://vuejs.org/v2/guide/components-props.html#Prop-Types

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +    },
the computed property name shouldn't a `verb`
```suggestion
    currencies() {
      return this.currencyCodes.map((item) => item.cc);
    },
```

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +    },
And we don't need `currency` as a data property

2021-06-30 07:00 UTC, truonghungit commented on src/companies/components/currency.js
> +  { cc: "AED", symbol: "\u062f.\u0625;", name: "UAE dirham" },
This is not a component, so please move it out of the components folder,

2021-06-30 07:00 UTC, truonghungit commented on src/companies/views/RegisterCompany.vue
> +      e1: 1,
`e1` ??

2021-06-30 07:00 UTC, truonghungit commented on src/companies/views/RegisterCompany.vue
> +import RegisterForm from "../components/RegisterCompanyForm.vue";
```suggestion
import RegisterCompanyForm from "../components/RegisterCompanyForm.vue";
```

2021-06-30 07:00 UTC, truonghungit commented on src/companies/views/RegisterCompany.vue
> +    RegisterForm,
```suggestion
    RegisterCompanyForm,
```

2021-06-30 07:00 UTC, truonghungit commented on src/companies/views/RegisterCompany.vue
> +}
as I understand, `.pdbt` mean `padding bottom top 40` so why `padding-bottom: 0px;` 
This is a utility class, can you move it to the share module to reuse it? the same for fs35, ...

2021-06-30 07:00 UTC, truonghungit commented on src/companies/views/RegisterCompany.vue
> +      });
```suggestion
    register(value) {
      this.e1 = 3;
      this.$store.dispatch("companies/register", value);
```

We don't need to create a new object again

2021-06-30 07:05 UTC, truonghungit commented
> ## 007 Create company screen 👋
> I have done build UI, handle post API to server.
> 
> ## Demo 📺
> **[Loom Video Demo](https://www.loom.com/share/c07c0956797940c6923455b8773ba469)**

` ## 007 Create company screen 👋` You shouldn't change the title. The title always is **Change description  👋`

2021-06-30 07:10 UTC, truonghungit commented on src/companies/components/BaseButton.vue
> +<style></style>
If you want to make it a base button, you should 
- have a prop or slot for button text, for example `<BaseButton>Create</BaseButton>  <BaseButton>Edit</BaseButton>`. I think the slot is good
- Have a prop for href,

2021-06-30 08:35 UTC, nguyenvinhduyet commented on src/companies/views/RegisterCompany.vue
> +}
thanks for your review, I have split into style.css file in shared folder

2021-06-30 23:20 UTC, truonghungit approved these changes

2021-06-30 23:20 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +    },
we should remove any code that is no longer in use.

2021-06-30 23:20 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +    },
we should remove any code that is no longer in use.

2021-06-30 23:20 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +      currencyCodes: currencyCodes,
can you check again? maybe we don't need the currency codes here
```suggestion
```

2021-06-30 23:20 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +    },
```suggestion
    currencies() {
      return currencyCodes.map((item) => item.cc);
    },
```

2021-06-30 23:20 UTC, truonghungit commented on src/companies/store/companies.js
> +  SET_SUCCESSFUL_MESSAGE() {},
Don't do anything? Can we remove it?

2021-06-30 23:20 UTC, truonghungit commented on src/companies/store/companies.js
> +        alert("Thành công");
We should not use native alerts. You can use Vue toaster 

- https://ankurk91.github.io/vue-toast-notification/
- https://vuejsexamples.com/tag/toast/

Please review the demo and select the best option for you.

2021-06-30 23:20 UTC, truonghungit commented on src/http/companies.js
> +const register = (companyInfor) =>
can you rename the `register` function to `create`

2021-06-30 23:20 UTC, truonghungit commented on src/shared/style/style.css
> +}
You'll need to refer to the naming conventions.
https://getbootstrap.com/docs/5.0/utilities/spacing/

2021-06-30 23:23 UTC, truonghungit requested changes
Lood good to me, I just leave some comments

2021-07-01 02:50 UTC, nguyenvinhduyet commented on src/companies/components/RegisterCompanyForm.vue
> +      currencyCodes: currencyCodes,
hello mentor, i was check, if i remove this currencyCodes here, program will have error.

2021-07-01 07:21 UTC, luantc13 approved these changes
Nice work!

2021-07-01 07:31 UTC, truonghungit approved these changes
good job

2021-07-01 07:31 UTC, merged