#008 company list screen
ezteksoftware/painite pull request #19
Opened 2021-07-02 08:24 UTC by elvisnguy

## Change Description 👋

I built Company List UI, made a request to API to get company list by Vuex logic, shown the loading progress bar when making a request call & Merge with master

## Demo 📺

https://www.loom.com/share/77cd2e0701584f9e962e660fff9680b5

Bring clarity to the code with visual aids:

![image](https://user-images.githubusercontent.com/56434398/124244822-8d05df80-db49-11eb-8f37-536bf78b4401.png)
run nprogress bar

2021-07-02 09:54 UTC, truonghungit requested changes

2021-07-02 09:54 UTC, truonghungit commented on src/Dashboard/components/NavBar.vue
> +        to: "/companies/123/setting",
we should get current company id instead hard code `123`

2021-07-02 09:54 UTC, truonghungit commented on src/companies/components/CompaniesTable.vue
> +  props: ["items"],
We should set type for prop

[components props](https://vuejs.org/v2/guide/components-props.html)

2021-07-09 07:29 UTC, truonghungit approved these changes

2021-07-09 07:32 UTC, luantc13 approved these changes
Nice work!

2021-07-09 08:00 UTC, merged