#004 setup axios
ezteksoftware/painite pull request #2
Opened 2021-06-14 07:06 UTC by elvisnguy

## Change Description 👋
Setup & Install Axios, test fake api.

## Demo 📺
https://www.loom.com/share/809f44585e6a4fdb9ad6af85b969cd69

Bring clarity to the code with visual aids:
![image](https://user-images.githubusercontent.com/56434398/121852112-31e68700-cd19-11eb-9b11-247e9c9f11a7.png)
![image](https://user-images.githubusercontent.com/56434398/121852240-62c6bc00-cd19-11eb-8609-e5c65fb1bc2c.png)

2021-06-14 07:30 UTC, truonghungit commented on src/main.js
> +
? ?

2021-06-14 07:32 UTC, truonghungit requested changes
Look good Thanh, but please follow the git commit message convention 
also, you should create the Axios instance to use

2021-06-14 07:32 UTC, truonghungit commented on db.json
> +}
We will using the real API, so please remove this file

2021-06-14 11:49 UTC, elvisnguy commented on db.json
> +}
Ok sir, i'm just created Axios instance and push new code. Sorry for my late, because i'm search google and test several time.
https://www.loom.com/share/3724087f066b453e989fde6748016742
![image](https://user-images.githubusercontent.com/56434398/121887618-260ebb00-cd41-11eb-8b44-1b603dda50b0.png)
![image](https://user-images.githubusercontent.com/56434398/121887633-2c9d3280-cd41-11eb-825c-d7d406c2fca8.png)
Tks for your review.

2021-06-15 07:25 UTC, truonghungit approved these changes

2021-06-15 07:32 UTC, nguyenvinhduyet approved these changes

2021-06-15 07:36 UTC, merged