feature:create update user profile form
ezteksoftware/painite pull request #20
Opened 2021-07-02 10:59 UTC by halfangel37

I created update user profile form , it have 2 fields to update is first name and last name (task 035) but I also do the image upload ( task 046 ) in it , can I do that to prepare for task 046 or I need to delete that part of code, and one more thing the vuetify grid system do not include the ipad pro so it seem pretty small , do I need to fix it.
 ##  Demo 📺

https://www.loom.com/share/cf141fec5bd04bbba953fb5940fee1c7

2021-07-04 02:30 UTC, truonghungit requested changes
![image](https://user-images.githubusercontent.com/9523581/124371276-68754900-dcaa-11eb-8204-f2928961135a.png)

Please check again

2021-07-04 02:30 UTC, truonghungit commented on src/profile/store/index.js
> +    userName: { firstName: "", lastName: "" },
?? 
You should save all user properties to `user`. I don't know why the username content the first name & last name?

![image](https://user-images.githubusercontent.com/9523581/124371209-a45bde80-dca9-11eb-9337-d9402adcfd84.png)

2021-07-04 02:30 UTC, truonghungit commented on src/profile/store/index.js
> +      console.log("image", data);
remove console log,

2021-07-04 02:30 UTC, truonghungit commented on src/profile/store/index.js
> +          commit("GET_USER_PROFILE", response.data);
I think `SET_USER_PROFILE` is better for this case

2021-07-04 02:30 UTC, truonghungit commented on src/profile/store/index.js
> +          commit("GET_USER_PROFILE", response.data);
use `SET_USER_PROFILE`

2021-07-04 02:30 UTC, truonghungit commented on src/profile/store/index.js
> +          console.log("error", error.response.data);
remove console log

2021-07-05 03:33 UTC, halfangel37 commented on src/profile/store/index.js
> +    userName: { firstName: "", lastName: "" },
![image](https://user-images.githubusercontent.com/28900958/124414058-1ef52e80-dd7c-11eb-9ade-5046b486c8f5.png)
in the put API link , we can only change 2 fields first name and last name , I could get username/email but cannot change it, so i think we just need 2 fields to update

2021-07-05 08:07 UTC, luantc13 requested changes
Nice work!

2021-07-06 09:11 UTC, truonghungit requested changes

2021-07-07 03:09 UTC, luantc13 approved these changes
Nice work!

2021-07-07 03:27 UTC, truonghungit approved these changes

2021-07-07 03:37 UTC, dtngoc99 approved these changes

2021-07-07 03:42 UTC, merged