feaure: Create Employee Screen
ezteksoftware/painite pull request #21
Opened 2021-07-02 12:01 UTC by nguyenvinhduyet

## Change Description 👋

Create employee screen almost done, I need your advice/comments to make it better

## Demo 📺

**[Loom Video Demo](https://www.loom.com/share/0124c1c26978406ab2efeb99e1e3c40f)**

Bring clarity to the code with visual aids:

-   **Screenshots:** `cmd` + `shift` + `4` _(MacOS)_.
-   **Gifs:** [GIPHY Capture](https://giphy.com/apps/giphycapture) _(free/MacOS)_.

2021-07-04 02:54 UTC, truonghungit requested changes

2021-07-05 07:23 UTC, luantc13 requested changes
Nice work!

2021-07-05 07:23 UTC, luantc13 commented on src/Dashboard/components/NavBar.vue
> +        to: `/companies/employees`,
I think this route is not correct.

2021-07-05 07:23 UTC, luantc13 commented on src/http/employees.js
> +}
We can have another approach, no need to have this function.

2021-07-05 11:58 UTC, nguyenvinhduyet commented on src/Dashboard/components/NavBar.vue
> +        to: `/companies/employees`,
sr, i changed to test but i forgot to remove them

2021-07-05 11:58 UTC, nguyenvinhduyet commented on src/http/employees.js
> +}
yes, i'm fix

2021-07-05 12:07 UTC, nguyenvinhduyet commented
HI mentor, i change Loom video demo with new UI, handle error from server for user! I'm looking forward to hearing from you soon

2021-07-06 02:49 UTC, truonghungit requested changes

2021-07-06 02:49 UTC, truonghungit commented on src/employees/components/RegisterEmployeeForm.vue
> +      <v-btn color="#72418b" dark @click="onSubmit()" x-large>CREATE</v-btn>
As a primary form button, we should set type="submit" for **CREATE** button, then use the `@submit` in <v-from> event instead of `@click`

Check [Signin Form](https://github.com/ezteksoftware/painite/blob/aa0d48609ac76d8cc5080c646abeccfea1b179a0/src/signin/components/SigninForm.vue#L15)

2021-07-06 02:49 UTC, truonghungit commented on src/employees/components/RegisterEmployeeForm.vue
> +      nameRules: [validators.required("Name company is required")],
`Employee name` NOT `Name company`

but there are first name and last name, therefore should have two rules, one for the first name and one for the last name

```suggestion
      firstNameRules: [validators.required("First name is required")],
      lastNameRules: [validators.required("Last name is required")],
```

2021-07-06 02:49 UTC, truonghungit commented on src/employees/components/RegisterEmployeeForm.vue
> +    },
Should check to validate before submitting the form

Check [Signin form](https://github.com/ezteksoftware/painite/blob/aa0d48609ac76d8cc5080c646abeccfea1b179a0/src/signin/components/SigninForm.vue#L91)

2021-07-06 02:49 UTC, truonghungit commented on src/employees/store/employees.js
> +Vue.use(Vuex);
Don't need to init Vuex again 
```suggestion
```

2021-07-06 02:49 UTC, truonghungit commented on src/employees/store/employees.js
> +              break;
We should validate the form before submit, so we don't need this case

2021-07-06 02:49 UTC, truonghungit commented on src/employees/views/RegisterEmployee.vue
> +        <RegisterEmployeeForm @create-employee="register" />
I think `CreateEmployee` and `CreateEmployeeForm` will make sense

2021-07-06 02:49 UTC, truonghungit commented on src/employees/views/RegisterEmployee.vue
> +        <RegisterEmployeeForm @create-employee="register" />
```suggestion
        <CreateEmployeeForm @submit="onCreateEmployee" />
```

2021-07-06 02:49 UTC, truonghungit commented on src/views/Employees.vue
> +};
Using the `EmployeesDashboard` component in the router configuration and we can remove this component

2021-07-06 02:49 UTC, truonghungit commented on src/store.js
> +import * as employees from "@/employees/store/employees.js";
Rename file the `store/employees.js` to `store/index.js`
Then we can import as below 
```suggestion
import * as employees from "@/employees/store";
```

2021-07-06 02:49 UTC, truonghungit commented on src/router/index.js
>          component: () => import("../views/Employees.vue"),
```suggestion
        component: () => import("../employees/views/EmployeesDashboard.vue"),
```

we can rename component `EmployeesDashboard` to `Employees`

2021-07-06 02:49 UTC, truonghungit commented on src/router/index.js
> +        path: ":companyId/contacts",
good

2021-07-06 02:49 UTC, truonghungit commented on src/http/employees.js
> +  );
More simple
```suggestion
  httpClient.post(`${COMPANY}/${companyId}/${EMPLOYEE}` employeeInfo );
```

2021-07-06 02:49 UTC, truonghungit commented on src/employees/views/RegisterEmployee.vue
> +      });
```suggestion
    register(employee) {
      this.$store.dispatch("employees/createEmployee", {
        employee,
        companyId: this.$route.params.companyId,
      });
```

2021-07-06 02:49 UTC, truonghungit commented on src/employees/store/employees.js
> +            case 409:
Should use the [HTTP status code constant](https://github.com/ezteksoftware/painite/blob/master/src/http/status-code.js)

2021-07-06 02:49 UTC, truonghungit commented on src/employees/store/employees.js
> +        commit("");
```suggestion
```

Remove commit("") if you don't commit any thing

2021-07-06 02:49 UTC, truonghungit commented on src/employees/store/employees.js
> +Vue.use(VueToast);
We should init the plugin once.  the same with https://github.com/ezteksoftware/painite/blob/master/src/plugins/vuetify.js

2021-07-06 02:49 UTC, truonghungit commented on src/employees/components/RegisterEmployeeForm.vue
> +}
Remove if we don't use this.

2021-07-06 02:49 UTC, truonghungit commented on src/employees/components/RegisterEmployeeForm.vue
> +}
check again and remove this if we don't use any wheree

2021-07-06 02:54 UTC, nguyenvinhduyet commented on src/employees/components/RegisterEmployeeForm.vue
> +      <v-btn color="#72418b" dark @click="onSubmit()" x-large>CREATE</v-btn>
yep, thanks mentor, i fixed

2021-07-06 05:20 UTC, nguyenvinhduyet commented on src/http/employees.js
> +  );
thanks for your feedback, but here, when change them, we will need to export COMPANY and EMPLOYEE at endpoint.js. I tried to change but it doesn't work

2021-07-06 07:40 UTC, truonghungit approved these changes
Good job 
just delete file `src\views\Employees.vue`  if we don't use it

2021-07-06 07:49 UTC, luantc13 approved these changes
Nice work!

2021-07-06 07:51 UTC, merged