Fix/change navigation
ezteksoftware/painite pull request #27
Opened 2021-07-06 08:19 UTC by dtngoc99

## Change Description 👋

Change the navigation
Change the notification way

## Demo 📺

**[Loom Video Demo](https://www.loom.com/share/8eb5989e2b374561938d975b409612f6)**

2021-07-06 10:55 UTC, luantc13 approved these changes
Great work!

2021-07-06 11:41 UTC, truonghungit requested changes
good job 👌, Just add  some comments

2021-07-06 11:41 UTC, truonghungit commented on src/profile/components/ChangePasswordForm.vue
> +      formValidity: false,
can you check again. remove if we don't use `formValidity`

2021-07-06 11:41 UTC, truonghungit commented on src/profile/components/ChangePasswordForm.vue
> +          "Password must not match!",
That good but I have confused, I don't know the password should not match which one?
```suggestion
          "New password and existing password should not be the same!",
```

2021-07-06 11:41 UTC, truonghungit commented on src/profile/components/ChangePasswordForm.vue
> +        validators.mustMatch("Password isn't match!", () => this.newPassword),
same above

2021-07-06 11:41 UTC, truonghungit commented on src/profile/store/index.js
> +            position: "top-right",
Can we set this configuration once?
Then 
```
          Vue.$toast.open({
            message: "message here",
            type: "error"
          });
```

2021-07-06 11:41 UTC, truonghungit commented on src/profile/store/index.js
> +          });
the same above

2021-07-06 11:41 UTC, truonghungit commented on src/shared/form-validators/index.js
> +};
We don't only use this function for the password but also use it for other cases, so the param `getPassword` is not good. It will be good if we can pass the string value or function to param `getPassword`

```suggestion
const mustNotMatch = (notMatchTo, errorMessage) => (value) => {
 const notMatchValue = typeof notMatchTo === 'function' ? notMatchTo() : notMatchTo;
  return value !== notMatchValue || message;
};
```

2021-07-07 08:31 UTC, truonghungit approved these changes

2021-07-07 08:32 UTC, merged