Feature/015 create product screen
ezteksoftware/painite pull request #32
Opened 2021-07-09 04:22 UTC by halfangel37

Except the Image Url still depend on backend , tell me if anything wrong with the frontend.
Demo:
https://www.loom.com/share/31624e403e254bee85904072742b7459

2021-07-09 04:53 UTC, truonghungit approved these changes
All good, just small comments, please resolve before merge into the main

2021-07-09 04:53 UTC, truonghungit commented on src/product/views/CreateProduct.vue
> +  }),
`isButtonDisabled` is not clear, rename to `isPending` that means we are waiting for the request to the server

2021-07-09 04:53 UTC, truonghungit commented on src/product/components/CreateProductForm.vue
> +    switchLabel: ["Enabled", "Disabled"],
```suggestion
```
Remove if we don't use

2021-07-09 04:53 UTC, truonghungit commented on src/product/components/CreateProductForm.vue
> +    type: ["Item", "Service"],
```suggestion
    productTypes: ["Item", "Service"],
```

2021-07-09 05:07 UTC, luantc13 requested changes
Nice work!
However, there are a big issue - `product_prices` here. Pls resolve ít and we can merge after that.

2021-07-09 05:07 UTC, luantc13 commented on src/product/components/CreateProductForm.vue
> +    ></v-select>
`product_prices` is a list, with many pairs of `currency - price`, pls re-implement this form.

2021-07-13 07:43 UTC, luantc13 approved these changes
Nice work!

2021-07-13 07:45 UTC, merged