fixed conflict
ezteksoftware/painite pull request #34
Opened 2021-07-12 10:05 UTC by elvisnguy

## Change Description 👋
Fixed conflict, choose company accord ID in url.

## Demo 📺
https://www.loom.com/share/d93bdb38322c4df0999a976744dce897

2021-07-12 14:56 UTC, truonghungit requested changes
Please check again

2021-07-12 14:56 UTC, truonghungit commented on src/router/index.js
> +export default router;
Please double-check router config again, seem it has issues
By the way, we should combine all of the company's routes into one.

Example
```
{
        path: ":companyId",
        component: () => import ("../companies/views/CompanyLayout.vue"),
        children: [
          {
            path: "products",
            component: () =>
              import ("../views/Products.vue"),
          },
          {
            path: "sales",
            component: () =>
              import ("../views/Sales.vue"),
          },
          {
            path: "fees",
            component: () =>
              import ("../views/Fees.vue"),
          },
        ]
      },
```

2021-07-12 14:56 UTC, truonghungit commented on src/http/httpClient.js
> +httpClient.interceptors.request.use(authInterceptor);
Nothing has changed

2021-07-12 14:56 UTC, truonghungit commented on src/http/endpoints.js
> +export const COMPANY_ENDPOINT = "/companies";
Nothing has changed

2021-07-12 14:56 UTC, truonghungit commented on src/companies/store/index.js
> +  },
What are we going to do with `storeID` action and `STORE_ID`  mutation?

2021-07-12 14:56 UTC, truonghungit commented on src/companies/components/ShowCompanies.vue
> +      :items="items"
`items` is undefined

2021-07-12 14:56 UTC, truonghungit commented on src/companies/components/RowsPerPage.vue
> +        :items="items"
`items` is undefined

2021-07-14 10:12 UTC, elvisnguy commented on src/companies/store/index.js
> +  },
I have removed it.

2021-07-14 11:06 UTC, luantc13 requested changes
Nice work!

2021-07-14 11:06 UTC, luantc13 commented on src/Dashboard/components/NavBar.vue
> +    // },
Pls remove un-used code.

2021-07-14 11:06 UTC, luantc13 commented on src/companies/components/RowsPerPage.vue
> +      debugger;
Pls remove `debugger`.

2021-07-14 11:06 UTC, luantc13 commented on src/companies/store/index.js
> +  company: {},
What is this property serve for?

2021-07-14 11:06 UTC, luantc13 commented on src/companies/store/index.js
> +
Redundant empty line.

2021-07-14 11:06 UTC, luantc13 commented on src/http/companies.js
> +  return httpClient.get(`${COMPANY_ENDPOINT}?PageNumber=${PageNumber}&PageSize=${PageSize}`)
Pls use the second parameter to pass the request params.

2021-07-14 11:06 UTC, luantc13 commented on src/http/httpClient.js
> +httpClient.interceptors.request.use(authInterceptor);
We should have an empty line at the end of all files.

2021-07-14 11:06 UTC, luantc13 commented on src/router/index.js
> +      }, {
I don't like this format, can you move `{` to a new line?

2021-07-14 11:06 UTC, luantc13 commented on src/router/index.js
> +      }, {
The same here.

2021-07-14 11:06 UTC, luantc13 commented on src/router/index.js
> +      // },
Pls remove unused code.

2021-07-14 17:14 UTC, elvisnguy commented on src/Dashboard/components/AppBar.vue
> +          >
because selectCompany get ID and changeCompany change UI when we do click event. I've tried only selectCompany but it's select ID and can't change UI when choose company

2021-07-14 17:22 UTC, elvisnguy commented on src/Dashboard/components/AppBar.vue
> +    },
I've removed it.

2021-07-14 17:24 UTC, elvisnguy commented on src/Dashboard/components/NavBar.txt
> +<template>
I've removed it.

2021-07-14 17:27 UTC, elvisnguy commented on src/Dashboard/components/NavBar.vue
>        },
Because I've tried to put params id into this url but now I don't anymore, I'll remove it and use "..."

2021-07-14 17:29 UTC, elvisnguy commented on src/router/index.js
> +      }, {
Let me try to setting it again

2021-07-14 17:30 UTC, elvisnguy commented on src/router/index.js
> +      // },
Done

2021-07-14 17:32 UTC, elvisnguy commented on src/companies/components/RowsPerPage.vue
> +      debugger;
Done

2021-07-14 17:44 UTC, elvisnguy commented on src/companies/store/index.js
> +  company: {},
companies:[] - Contains company information when we call an API to get company.
selectedCompanyId: - State set undefined but when we do click event then getter "selectedCompany" will find company's ID match with "selectedCompanyId" state and get it.
company:{} - this property serve for change UI when we do click event.

2021-07-14 17:44 UTC, elvisnguy commented on src/companies/store/index.js
> +
removed

2021-07-15 04:56 UTC, elvisnguy commented on src/http/companies.js
> +  return httpClient.get(`${COMPANY_ENDPOINT}?PageNumber=${PageNumber}&PageSize=${PageSize}`)
Done

2021-07-15 05:01 UTC, elvisnguy commented on src/Dashboard/components/NavBar.vue
> +    // },
done

2021-07-15 08:28 UTC, luantc13 approved these changes
Nice work!

2021-07-15 09:36 UTC, truonghungit commented
![image](https://user-images.githubusercontent.com/9523581/125765463-56dc6504-6c85-4aca-85e3-1a65d9737ccd.png)
@elvisnguy  When we don't have any company yet, we should navigate to create a new company page. Please check `demo` again

2021-07-15 09:47 UTC, truonghungit commented
![2021-07-15_16-43-52](https://user-images.githubusercontent.com/9523581/125767374-a9124c97-4130-4116-a518-3c86bdf60a90.gif)

![image](https://user-images.githubusercontent.com/9523581/125767655-410c01a0-8eb5-41b3-90d2-ca68a08f05ec.png)

Layout is not responsive on desktop. Let me create new task

2021-07-16 10:55 UTC, truonghungit approved these changes

2021-07-16 11:37 UTC, merged