Feature/creating product list screen
ezteksoftware/painite pull request #35
Opened 2021-07-14 08:02 UTC by dtngoc99

## Change Description 👋

Creating products screen such as
- Show all product,
- Filter product, 
- Search product, 
- Delete product,
- Change product status, 
- Navigate to other page when click any row from table

## Demo 📺

https://loom.com/share/82d7a6e003144404bc56c1d9a44a4cc3

2021-07-14 09:30 UTC, luantc13 requested changes
Great work!
Having some comments, happy to merge when they are resolved.

2021-07-14 09:30 UTC, luantc13 commented on src/http/products.js
> +    httpClient.get(`${COMPANY}/${id}${PRODUCTS}?PageNumber=${PageNumber}&PageSize=${PageSize}`)
Should do we have `return` here?

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +    state.products[index].status=status;
Not a good format. `...status = status;`

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +  RESET_PRODUCT_STATE(state,{product,status}){
Not a good format. `...(state, { product, status }) {`

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +      });
Pls don't directly use `httpClient` here.

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +      });
The same here, pls don't directly use `httpClient`.

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +      });
The same here, pls don't directly use `httpClient`.

2021-07-14 09:30 UTC, luantc13 commented on src/products/store/index.js
> +  product: {},
What is this property serve for?

2021-07-14 11:04 UTC, dtngoc99 commented on src/products/store/index.js
> +  product: {},
my fault

2021-07-14 16:07 UTC, truonghungit requested changes

2021-07-15 07:49 UTC, dtngoc99 commented
Update demo:
https://loom.com/share/5d205f5cc7ed4a4a826ab6e5ff33b395

2021-07-15 08:42 UTC, dtngoc99 commented
Update demo:

![image](https://user-images.githubusercontent.com/44255006/125757781-09c179a8-e0ea-4aca-900b-46ebf9193fd6.png)

2021-07-15 09:43 UTC, dtngoc99 commented
![image](https://user-images.githubusercontent.com/44255006/125766984-3472f08d-028e-4478-9b23-0de4a656c302.png)

2021-07-15 10:07 UTC, dtngoc99 commented
![image](https://user-images.githubusercontent.com/44255006/125770524-13e656ce-b768-485c-9117-582d7fdbe7a7.png)

2021-07-16 04:14 UTC, luantc13 approved these changes
Great work!

2021-07-16 04:14 UTC, luantc13 commented on src/filters/Filters.js
> +import Vue from "vue";
This file name should be `filter.js`.

2021-07-16 04:14 UTC, luantc13 commented on src/filters/Filters.js
> +Vue.filter('upperCase',upperCase)
Not a good format, and we should have an empty line at the end of file.

2021-07-16 04:14 UTC, luantc13 commented on src/products/components/Products.vue
> +        { text: "PRICE", value: "productPrices[0].price", sortable: false },
`productPrices` may be an empty list.

2021-07-16 07:19 UTC, dtngoc99 commented on src/filters/Filters.js
> +import Vue from "vue";
As you know, we can't rename the file, can i delete this file and create a new file?

2021-07-16 08:29 UTC, truonghungit requested changes

2021-07-16 08:29 UTC, truonghungit commented on src/products/components/Products.vue
> +      productChange: {},
The term "selectedProduct" will be more precise.
and init state should be `undefined`
```suggestion
      selectedProduct: undefined,
```

2021-07-16 08:29 UTC, truonghungit commented on src/store/index.js
>      product
`products` and `product` should be combined into a single store.

2021-07-16 08:29 UTC, truonghungit commented on src/products/store/index.js
> +};
`indexOf` will not work correctly. Please use **findIndex**  when you want to find the index of the object in the array.
because indexOf() compares searchElement to elements of the Array using [strict equality](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) (the same method used by the === or triple-equals operator).

[Array IndexOf document](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf)

example 
```
var products = [
	{id: 1, name: "p 1"},
	{id: 2, name: "p 2"},
	{id: 3, name: "p 3"},
	{id: 4, name: "p 4"},
	{id: 5, name: "p 5"},
];

var index = products.indexOf({id: 2, name: "p 2"});
console.log("indexOf: ", index); // => -1

var index2 = products.findIndex((p) => p.id == 2);
console.log("indexOf: ", index2); // => 1

console.log(products[1] == {id: 2, name: "p 2"}); // => false    
console.log(products[1] == products[1]); // => true
```

2021-07-16 08:29 UTC, truonghungit commented on src/http/products.js
> +};
As I see this method just update the status of the product, not update all properties, so if you just want to update status => change the name to **updateStatusProduct**
if you want to keep the **pathUpdateProduct** name => you should change the params and some things to support update other product property

2021-07-19 03:43 UTC, luantc13 commented on src/filters/Filters.js
> +import Vue from "vue";
yes, I agree with this option.

2021-07-19 05:57 UTC, dtngoc99 commented on src/store/index.js
>      product
Because Vinh are fixing some things for product, so can we combine this after Vinh finished it.

2021-07-19 06:12 UTC, dtngoc99 commented
Update demo:

https://loom.com/share/5d0437bb462b4b2497601ee81e47e94f

2021-07-19 07:42 UTC, dtngoc99 commented
Update demo:

https://www.loom.com/share/e788726eaf20403fb83b657920f2bfa9

2021-07-19 12:09 UTC, truonghungit commented
There is error when run `yarn serve`

![image](https://user-images.githubusercontent.com/9523581/126157618-54fd1c97-4b28-41c2-9f3b-1ab7dd6f45bd.png)

2021-07-19 12:33 UTC, dtngoc99 commented
> There is error when run `yarn serve`
> 
> ![image](https://user-images.githubusercontent.com/9523581/126157618-54fd1c97-4b28-41c2-9f3b-1ab7dd6f45bd.png)

Sorry for this problem, I have changed but forgot commit again

2021-07-21 02:06 UTC, truonghungit approved these changes

2021-07-21 02:08 UTC, truonghungit commented
@dtngoc99 please wait for [pr #40](https://github.com/ezteksoftware/painite/pull/40)

2021-07-21 05:32 UTC, merged