feature:Create update product screen
ezteksoftware/painite pull request #36
Opened 2021-07-15 09:58 UTC by halfangel37

feature:Create update product screen

## Demo 📺

https://www.loom.com/share/6507e271d9bc46f7889650b163d8e98e

2021-07-15 10:50 UTC, luantc13 requested changes
Nice work!
Having some small comments, happy to merge when they are resolved.

2021-07-15 10:50 UTC, luantc13 commented on src/shared/form-validators/index.js
> +};
`0` is also a number. I think you should have a validator called "requiredPositiveNumber`.

2021-07-15 10:50 UTC, luantc13 commented on src/product/views/UpdateProduct.vue
> +
A redundant empty line.

2021-07-15 10:50 UTC, luantc13 commented on src/product/views/UpdateProduct.vue
> +
A redundant empty line.

2021-07-15 10:50 UTC, luantc13 commented on src/product/store/index.js
> +        });
I don't think we should use `httpClient` directly.

2021-07-15 10:50 UTC, luantc13 commented on src/product/components/UpdateProductForm.vue
> +    },
`currencies` and `currenciesArray` make me confused, pls rename `currenciesArray` to `productCurrencies`.

2021-07-15 10:50 UTC, luantc13 commented on src/product/components/UpdateProductForm.vue
> +
A redundant empty line.

2021-07-15 13:47 UTC, truonghungit commented
the first time does not show any things 
 https://www.loom.com/share/e8ec85eadc8f498b9f034a4c6f5eb050

2021-07-19 11:23 UTC, luantc13 requested changes
Nice work!
Having some comments, happy to merge when they are resolved.

2021-07-19 11:23 UTC, luantc13 commented on src/product/views/CreateProduct.vue
> +    createProduct(product, File) {
I don't think `File` is a good name, pls rename it to `formData`.

2021-07-19 11:23 UTC, luantc13 commented on src/http/products.js
> +};
I don't think `File` is a good name, pls rename it to `formData`.

2021-07-19 11:23 UTC, luantc13 commented on src/product/components/UpdateProductForm.vue
> +          this.product.imageName
This is hard to read, may we use another approach?

2021-07-19 11:23 UTC, luantc13 commented on src/product/store/index.js
> +          commit("GET_PRODUCT_ID", response.data.id);
`GET_PRODUCT_ID`? Why do we need this mutation?

2021-07-19 11:23 UTC, luantc13 commented on src/profile/components/UserProfileForm.vue
> +        v-model="cloneUser.imageName"
They are have the different data type.

2021-07-19 11:23 UTC, luantc13 commented on src/profile/components/UserProfileForm.vue
> +      cloneUser: "",
`cloneUser` is an object, not a string.

2021-07-20 04:26 UTC, halfangel37 commented on src/http/endpoints.js
> +export const DELETE_COMPANY_ENDPOINT = "/companies";
export const DELETE_COMPANY_ENDPOINT = "/companies";
its already in master branch, I pull master and it was there.

2021-07-20 08:26 UTC, luantc13 approved these changes
Great work!

2021-07-20 08:26 UTC, luantc13 commented on src/product/store/index.js
> +          let productId = response.data.id;
I think we should replace `let` with `const`, I see that `productId` is only assigned a value once.

2021-07-20 08:26 UTC, luantc13 commented on src/product/store/index.js
> +    product: { imageName: "" },
Pls explain more about the default value of `imageName`.

2021-07-20 08:31 UTC, halfangel37 commented on src/product/store/index.js
> +    product: { imageName: "" },
I do it before to make the image change reactively, but not I check it again and see that I dont need it , i just need the 
![image](https://user-images.githubusercontent.com/28900958/126288587-e7f8e26b-69f9-43e1-9235-d2fb6cd39192.png)
to make it reactively, so I will delete it.

2021-07-21 02:08 UTC, truonghungit approved these changes

2021-07-21 02:09 UTC, truonghungit commented
@halfangel37 please wait for [PR #40](https://github.com/ezteksoftware/painite/pull/40)

2021-07-21 09:26 UTC, merged