#002 create register screen
ezteksoftware/painite pull request #4
Opened 2021-06-21 10:56 UTC by halfangel37

## Change Description 👋

First Name , Last Name , Email (UserName), Password, validate input

## Demo 📺

https://www.loom.com/share/5936d9a7cb7b421ca95098baef4728b7

it worked without bug before , i dont know where the 403 status come from.

2021-06-21 14:22 UTC, truonghungit requested changes
Nice work @halfangel37
I've left quite a few comments so let me know if anything is unclear.
Also, please 
- Add me as a reviewer when creating a PR
- Follow Git branch naming convention
- Follow Git commit message convention

2021-06-21 14:31 UTC, truonghungit commented
> it worked without bug before , i dont know where the 403 status come from.

@halfangel37  Let investigate and fix it, you shouldn't leave this message in the pull request. You can ask me, or the team to support

2021-06-21 15:07 UTC, truonghungit commented on src/store.js
> +          console.log(error.response);
When the user registers success/failure, please check the response and present a message to them. Also remove console log here

![image](https://user-images.githubusercontent.com/9523581/122783839-20cee480-d2dc-11eb-857e-c453510c45d2.png)

2021-06-21 15:07 UTC, truonghungit commented on src/store.js
> +          commit("SET_USER_DATA", data);
Don't need to save user data

2021-06-21 15:07 UTC, truonghungit commented on src/store.js
> +    user: null,
for what? angel

2021-06-21 15:11 UTC, truonghungit commented on src/views/Register.vue
> +      required: (value) => !!value || "The field is required.",
![image](https://user-images.githubusercontent.com/9523581/122785193-5de7a680-d2dd-11eb-85f8-7cc156022aab.png)

I passed your validation by space

2021-06-21 15:14 UTC, truonghungit commented on src/views/Register.vue
> +          </v-btn>
While calling the API, please deactivate the **Sign up** button and display the loading indicator.

2021-06-21 15:33 UTC, truonghungit commented on src/store.js
> +import Vue from "vue";
When our app grows in scale, the `src/store.js` file might get very large. Let's break it down into modules. 
In my view, you should have a file structure as below

![image](https://user-images.githubusercontent.com/9523581/122788367-74dbc800-d2e0-11eb-8123-a5b934604dc1.png)

I will explain more detail about this structure in zoom call tmr.

2021-06-21 15:35 UTC, truonghungit commented
The UI is not responsive on mobile. check again
![image](https://user-images.githubusercontent.com/9523581/122788846-f2073d00-d2e0-11eb-8aa8-26ded37c3fab.png)

2021-06-24 09:42 UTC, truonghungit requested changes

2021-06-24 09:42 UTC, truonghungit commented on src/register/components/RegisterForm.vue
> +      return this.$store.state.registerModule.errorMessage;
The Register form is a presentation component, it shouldn't access to state, dispatch an action or call API
You should get the error message in the `RegisterPage` component then you can
- display the error message in the `RegisterPage` component OR
- pass the error message to `RegisterForm` via props

and please use Getters to get data from state
https://vuex.vuejs.org/guide/getters.html#property-style-access

2021-06-24 09:47 UTC, truonghungit requested changes

2021-06-24 09:47 UTC, truonghungit commented on src/register/store/Register.js
> +export const registerModule = {
```suggestion
export default  {
```

2021-06-24 09:47 UTC, truonghungit commented on src/register/views/RegisterPage.vue
> +          <register-form @user-infor="register"></register-form>
The name of the event should be a verb. 
```suggestion
          <RegisterForm @on-submit="onSubmit" />
```

2021-06-25 08:51 UTC, luantc13 approved these changes
Nice work!

2021-06-25 08:51 UTC, luantc13 commented on src/register/store/Register.js
> +      commit("SET_ERROR_MESSAGE", "null");
`"null"` is a string with `null` content, pls use `null` or `""`.

2021-06-25 08:52 UTC, merged