refactor/refactor page container
ezteksoftware/painite pull request #41
Opened 2021-07-21 10:48 UTC by elvisnguy

## Change Description 👋
• Fix css page container

## Demo 📺
![image](https://user-images.githubusercontent.com/56434398/126476790-85a839ba-2d9b-4c22-9713-1c103afcf3eb.png)
![image](https://user-images.githubusercontent.com/56434398/126476810-91430ca8-b7a1-4f44-85b3-55a55bca0feb.png)
![image](https://user-images.githubusercontent.com/56434398/126476877-4cb1a6b3-e47b-48a6-b061-4456d66bc5da.png)
![image](https://user-images.githubusercontent.com/56434398/126476887-500401fa-ae34-4103-80d4-643fce1c3499.png)
![image](https://user-images.githubusercontent.com/56434398/126476943-ce99ba15-7fa4-4c2f-bfa2-fa700032e734.png)

2021-07-21 13:04 UTC, truonghungit commented
Please **double-check** again the demo, **TEST** before create a pull request.

https://www.loom.com/share/3ded61eaeca84249b91a4077b5aafdb9

2021-07-22 11:31 UTC, luantc13 requested changes
Nice work!
Still having some comments, we can merge after resolving all of them.

2021-07-22 11:31 UTC, luantc13 commented on src/companies/components/CompaniesTable.vue
> +        return this.companiesDisplay.indexOf(item) % 2 < 1 ? "bg-gray" : "bg-white";
`=== 0` is better.

2021-07-22 11:31 UTC, luantc13 commented on src/companies/components/SearchCompanies.vue
> +      console.log(value)
We should remove all `console.log` before commiting.

2021-07-22 11:31 UTC, luantc13 commented on src/companies/components/SearchCompanies.vue
> +    search:String,
Not a good formating.

2021-07-22 11:31 UTC, luantc13 commented on src/companies/views/ListCompaniesPage.vue
> +// import SearchCompanies from "@/companies/components/SearchCompanies.vue";
Pls remove all commented codes if we don't use them anymorre.

2021-07-22 11:31 UTC, luantc13 commented on src/employees/store/index.js
> +    }, ];
`payload` should be a `const`.

Btw, I prefer the old format.

2021-07-22 11:31 UTC, luantc13 commented on src/employees/store/index.js
> +};
All files should have an empty line at the end.

2021-07-22 11:31 UTC, luantc13 commented on src/layouts/dashboard/AppBar.vue
> +    },
I think we have a bad formating here.

2021-07-22 11:31 UTC, luantc13 commented on src/layouts/dashboard/AppBar.vue
> +    },
This method name should be `navigateToCompanieListPage`.

2021-07-22 11:31 UTC, luantc13 commented on src/products/views/CreateProduct.vue
> +  components: { CreateProductForm,PageContainer },
Bad formating.

2021-07-22 11:31 UTC, luantc13 commented on src/products/views/ProductsDashboard.vue
> +  components: { Products, CreateButton ,PageContainer},
The same here.

2021-07-22 11:31 UTC, luantc13 commented on src/router/index.js
> +export default router;
All files should have an empty line at the end.

2021-07-22 11:31 UTC, luantc13 commented on src/store/index.js
> +});
All files should have an empty line at the end.

2021-07-22 16:39 UTC, elvisnguy commented on src/employees/store/index.js
> +    }, ];
This "Employees" module did by Duyet, so we're discuss about this and resolve tomorrow

2021-07-22 16:43 UTC, elvisnguy commented on src/products/views/CreateProduct.vue
> +  components: { CreateProductForm,PageContainer },
Like above problem, Ngoc did this module so I'll discuss with her and fix on tomorrow morning

2021-07-22 16:43 UTC, elvisnguy commented on src/products/views/ProductsDashboard.vue
> +  components: { Products, CreateButton ,PageContainer},
Yeah, I got it.

2021-07-23 04:00 UTC, elvisnguy commented on src/router/index.js
> +export default router;
Let me setting or download new formatter later, I try to setting so many times but it can't working

2021-07-23 07:06 UTC, luantc13 approved these changes
Nice work!

2021-07-23 08:31 UTC, truonghungit approved these changes

2021-07-23 08:38 UTC, merged