feature/creating contact list screen
ezteksoftware/painite pull request #44
Opened 2021-07-23 11:46 UTC by dtngoc99

## Change Description 👋

Creating contact list screen with some actions such as:

- Show contact list
- Change customer status and supplier status
- Delete contact
- Search contact
- Filter contact by status

## Demo 📺

https://loom.com/share/74dc8ab43982436dbcbe3ba9d36ef559

2021-07-23 14:43 UTC, dtngoc99 commented
Update demo:

https://loom.com/share/639b3e7c67f64f508b00a34682a97094

2021-07-25 18:21 UTC, luantc13 commented
:stuck_out_tongue_winking_eye:
![image](https://user-images.githubusercontent.com/35829100/126909238-fbb4527a-4039-48c4-8154-bae891d7f69c.png)

2021-07-25 18:44 UTC, luantc13 requested changes
Great work!
Having some comments, happy to merge when they are resolved.

2021-07-25 18:44 UTC, luantc13 commented on src/contacts/components/Contacts.vue
> +          : "enable supplier status";
Pls, don't use this magic anymore, `if else` is the best choice here.

2021-07-25 18:44 UTC, luantc13 commented on src/contacts/store/index.js
> +const state = {
Empty lines to break the code to separate blocks are easier to read in the future.
An example, we can break this file into 6 blocks: `import`, `state`, `mutations`, `actions`, `getters`, and `export`.
Each block is separated by an empty line.

2021-07-25 18:44 UTC, luantc13 commented on src/contacts/store/index.js
> +    else state.contacts[index].supplierStatus = contactStatus;
We should have `{}` for all `if else` statements, it's a javascript convention.
```suggestion
    if (contactTypeChange === 0) {
      state.contacts[index].customerStatus = contactStatus;
    } else {
      state.contacts[index].supplierStatus = contactStatus;
    }
```

2021-07-25 18:44 UTC, luantc13 commented on src/http/contacts.js
> +export { getContacts, updateContactStatus ,deleteContact};
Not a good formating.

2021-07-25 18:44 UTC, luantc13 commented on src/http/endpoints.js
> +export const CONTACTS='/contacts'
All files should have an empty line at the end.

2021-07-25 18:44 UTC, luantc13 commented on src/plugins/nprogress.js
> +NProgress.configure({showSpinner:false})
All files should have an empty line at the end.

2021-07-25 18:44 UTC, luantc13 commented on src/products/store/index.js
> +    state.totalPages=0;
Not a good formating.

2021-07-25 18:44 UTC, luantc13 commented on src/router/index.js
> +    store.dispatch("products/clearAllStates");
I don't think that is a good idea when clearing all states `router.beforeEach`.
Just clear the necessary fields is too enough.

2021-07-25 18:44 UTC, luantc13 commented on src/store/index.js
>  });
All files should have an empty line at the end.

2021-07-26 02:34 UTC, dtngoc99 commented on src/contacts/store/index.js
> +const state = {
I will

2021-07-26 08:33 UTC, luantc13 approved these changes
Great work!

2021-07-26 09:38 UTC, truonghungit approved these changes

2021-07-26 09:47 UTC, merged