feature/update employee screen
ezteksoftware/painite pull request #45
Opened 2021-07-23 12:19 UTC by nguyenvinhduyet

## Change Description 👋

- Feature: update employee

## Demo 📺

**[Loom Video Demo](https://www.loom.com/share/c8cab56d77584cb28634e8f35c7c08f7)**

2021-07-25 18:46 UTC, luantc13 commented
We don't need to confirm enable/disable in the updating page.
![image](https://user-images.githubusercontent.com/35829100/126909930-61512843-7685-40e3-b05d-277d6b7d939e.png)

2021-07-25 18:48 UTC, luantc13 commented
What happens if we click to `Save` button after deleted the employee?

2021-07-25 18:58 UTC, luantc13 requested changes
Great work!
Having some comments, happy to merge when they are resolved.

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +      this.employeeCopy.birthDate = this.employeeCopy.birthDate.slice(0, 10);
What is this magic?

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +          : "Disable";
Pls, don't use this magic anymore, `if else` is the best choice here.

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +      this.dialogContent = `Are you sure you want to ${actionTypeName.toLowerCase()} the employee named "${this.employeeCopy.firstName +" "+ this.employeeCopy.lastName}"?`;
`${this.employeeCopy.firstName +" "+ this.employeeCopy.lastName}` is not a good approach.
Let's try with:
`${this.employeeCopy.firstName} ${this.employeeCopy.lastName}`

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +      this.dialogContent = `Are you sure want to delete the employee '${this.employeeCopy.firstName +" "+ this.employeeCopy.lastName}'?`
The same here.

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +      else return this.employeeCopy.status = DISABLE_STATUS
We should have {} for all if else statements, it's a javascript convention.

2021-07-25 18:58 UTC, luantc13 commented on src/employees/components/UpdateEmployeeForm.vue
> +      else return this.employeeCopy.status = DISABLE_STATUS
```suggestion
      if (this.employeeCopy.status === DISABLE_STATUS) {
        return this.employeeCopy.status = ENABLE_STATUS;
      } else {
        return this.employeeCopy.status = DISABLE_STATUS;
      }
```

2021-07-25 18:58 UTC, luantc13 commented on src/employees/store/index.js
> +  employee: {},
The default value should be `undefined`, not an empty object `{}`.

2021-07-25 18:58 UTC, luantc13 commented on src/employees/views/UpdateEmployee.vue
> +<style></style>
All files should have an empty line at the end.

2021-07-25 18:58 UTC, luantc13 commented on src/http/employees.js
> +export { create, getEmployees, updateStatusEmployee, deleteEmployee, updateEmployee, getEmployeeById }
All files should have an empty line at the end.

2021-07-25 18:58 UTC, luantc13 commented on src/products/components/UpdateProductForm.vue
> +      console.log(this.productCopy)
We should remove all `console.log` before commiting.

2021-07-26 03:05 UTC, nguyenvinhduyet commented
> What happens if we click to `Save` button after deleted the employee?
- It will display an error message: that this information does not exist
![image](https://user-images.githubusercontent.com/44804832/126927490-ce5c4f45-d1fe-4f8c-be4b-77d0854f6206.png)

-> Fix: after pressing the delete button I will be redirected to the employee list page

2021-07-26 07:19 UTC, luantc13 approved these changes
Nice work!

2021-07-26 08:24 UTC, truonghungit requested changes

2021-07-26 08:24 UTC, truonghungit commented on src/employees/components/UpdateEmployeeForm.vue
> +      </v-row>
We should align the delete button to the right 
![image](https://user-images.githubusercontent.com/9523581/126955411-8da4b77c-e4ca-40c6-aa4a-e771ff380d9c.png)


simple yet best solution

```suggestion
      <div class="d-flex justify-space-between">
        <div>
          <v-btn outlined color="#72418b" @click="cancelUpdateEmployee()" class="mr-5"
            >CANCEL</v-btn
          >

          <v-btn color="#72418b" dark type="submit" @click="validate()" class="mr-5"
            >SAVE</v-btn
          >
        </div>

        <v-btn outlined color="#F44336" @click="confirmDeleteEmployee(employeeCopy.id)"
          >DELETE</v-btn
        >
      </div>
```

2021-07-26 08:24 UTC, truonghungit commented on src/employees/components/UpdateEmployeeForm.vue
> +      </v-row>
I believe the component `CreateEmployeeForm` can be reused for updates, just rename it to `EmployeeForm` and update small things to binding data to UI (in edit mode), therefore we don't need the `UpdateEmployeeForm.vue`

in the CreateEmployee page, we will have
`<EmployeeForm @submit="onCreateEmployee" />`

in the UpdateEmployee page we will have
`<EmployeeForm :employee="employee" @submit="onUpdateEmployee" @delete-employee="onDeleteEmployee"/>`

2021-07-27 02:55 UTC, nguyenvinhduyet commented
video loom demo update: https://www.loom.com/share/22b13229dd734e5e847eb300d31d3e4d

2021-07-27 06:19 UTC, nguyenvinhduyet commented
Video demo update (fix: direct page "employee not found"): https://www.loom.com/share/873afc7534ab42978daeffd1fb62a275

2021-07-27 08:10 UTC, truonghungit approved these changes

2021-07-27 08:23 UTC, merged