Feature/024 bank account list screen
ezteksoftware/painite pull request #46
Opened 2021-07-26 11:16 UTC by halfangel37

## Create bank account list screen 👋

- Create bank account list screen 
- Refactor: Fix Profile Behavior, Apply PageContainer to Update Product

## Demo 📺

https://www.loom.com/share/f68f6b45da064ff0b05493de53853c75

https://www.loom.com/share/4b26d10f3b374372b2d3c354e68f3292

2021-07-26 16:23 UTC, luantc13 commented
That is weird when we use `,` to format the account number.

![image](https://user-images.githubusercontent.com/35829100/127024046-e19e932b-338a-4a0d-b63e-aefccfac080c.png)

2021-07-26 16:34 UTC, luantc13 commented
For simpler, we can remove three unnecessary tabs.

![image](https://user-images.githubusercontent.com/35829100/127025504-834deaf5-74b7-4217-b674-c7adf9790a0b.png)

2021-07-26 16:44 UTC, luantc13 requested changes
Great work!
Having some comments, happy to merge when they are resolved.

2021-07-26 16:44 UTC, luantc13 commented on src/companySetting/components/BankAccountsListForm.vue
> +    navigateBankAccount(bankAccount) {
That's not a good name, is `navigateToUpdateBankAccountPage` better?

2021-07-26 16:44 UTC, luantc13 commented on src/companySetting/store/index.js
> +const namespaced = true;
Empty lines to break the code to separate blocks are easier to read in the future.
An example, we can break this file into 6 blocks: `import`, `state`, `mutations`, `actions`, `getters`, and `export`.
Each block is separated by an empty line.

2021-07-26 16:44 UTC, luantc13 commented on src/companySetting/store/index.js
> +        const resetStatus = bankAccountStatus === 1 ? 0 : 1;
We should use `DISABLE_STATUS` and `ENABLE_STATUS` for all places.

2021-07-26 16:44 UTC, luantc13 commented on src/profile/components/UserProfileForm.vue
> +      profileCopy: "",
Why do you want to use an empty string `""` as a default value? `profileCopy` is an object, so the default value should be `undefined`.

2021-07-26 16:44 UTC, luantc13 commented on src/http/companySetting.js
> +import { httpClient } from "@/http/httpClient";
This http service should be `bankAccount.js`.

2021-07-26 16:44 UTC, luantc13 commented on src/companySetting/components/BankAccountsListForm.vue
> +<template>
`companySettings` is a better choice, it should be apply for all.

2021-07-26 16:44 UTC, luantc13 commented on src/router/index.js
> +                ],
Why do we need `children` with only one child path?

Could you try replacing `import("../views/Setting.vue")` with `import("../companySetting/views/CompanySetting.vue")`?

2021-07-27 00:01 UTC, truonghungit commented
Missing the page title 
![image](https://user-images.githubusercontent.com/9523581/127073692-2fa6fa24-3699-4ac3-8a58-6d4b60c29e45.png)

2021-07-27 02:25 UTC, truonghungit commented on src/router/index.js
> +                ],
We should remove `src/views`, please move it into company setting module

2021-07-28 01:05 UTC, truonghungit requested changes

2021-07-28 01:05 UTC, truonghungit commented on src/views/Setting.vue
please delete this file if we don't use

2021-07-28 01:05 UTC, truonghungit commented on src/views/Dashboard.vue
>  </script>
remove this file

2021-07-28 01:16 UTC, truonghungit commented
![image](https://user-images.githubusercontent.com/9523581/127247934-cc166153-8fef-4dec-9a4d-761df766b7b4.png)

2021-07-28 03:45 UTC, halfangel37 commented on src/companySettings/views/CompanySettings.vue
> +          <div class="container" :class="{ active: tab === 1 }">
I changed it to this , it for active the content when click on the tab bank account.
![image](https://user-images.githubusercontent.com/28900958/127260246-6da0556d-3b38-42df-9ee2-91ea8c15d0b1.png)

2021-07-28 03:59 UTC, luantc13 approved these changes
Great work!

2021-07-28 05:17 UTC, truonghungit approved these changes

2021-07-28 05:42 UTC, merged