Feature/update company screen
ezteksoftware/painite pull request #47
Opened 2021-07-28 03:33 UTC by elvisnguy

## Change Description 👋

• I did update company functionality
• Fixed pagination & create new company then navigate to company list, it's display new company

## Demo 📺

2021-07-28 05:47 UTC, truonghungit requested changes

2021-07-28 05:47 UTC, truonghungit commented on src/companies/components/CompaniesTable.vue
>      companiesDisplay: Array,
the `companies` prop is not used

2021-07-28 05:47 UTC, truonghungit commented on src/companies/components/CompaniesTable.vue
> +      this.$emit("delete-company", this.selectedCompany)
we should have a semi-colon at the end of the line;

2021-07-28 05:47 UTC, truonghungit commented on src/companies/components/RegisterCompanyForm.vue
> +      })
Even if the creation goes well, there's no assurance you'll get it because the request registration procedure may not be complete when a **get companies** request arrives.

And one thing: Don't dispatch any action in the presentation components (this is a **rule**).

2021-07-28 05:47 UTC, truonghungit commented on src/companies/components/UpdateCompanyForm.vue
> +    </v-col>
I wonder what this line of code is for?

2021-07-28 05:47 UTC, truonghungit commented on src/companies/views/UpdateCompany.vue
> +  </v-main>
The company settings page was merged into master, so please using the [CompanySettings](https://github.com/ezteksoftware/painite/blob/master/src/companySettings/views/CompanySettings.vue)

Place the `UpdateCompanyForm` into the correct tab on **CompanySettings page**

2021-07-28 07:16 UTC, elvisnguy commented on src/companies/components/RegisterCompanyForm.vue
> +      })
Yea, I will take notes and remember it.

2021-07-28 11:40 UTC, luantc13 approved these changes
Nice work!
Having some commented code, bad formatting, but they are not major issues.

2021-07-29 02:34 UTC, truonghungit approved these changes

2021-07-29 07:07 UTC, merged