feature/create contact screen
ezteksoftware/painite pull request #48
Opened 2021-07-28 05:49 UTC by dtngoc99

## Change Description 👋

-  Create new contact
-  Can select contact type
-  Can select status
-  Have no image
## Demo 📺

https://loom.com/share/3e6013ab0d62474ab79ac316974ce9c1

2021-07-28 07:07 UTC, truonghungit commented
![image](https://user-images.githubusercontent.com/9523581/127279263-400b0dc2-f92b-403b-8be7-99839c5061d3.png)

2021-07-28 07:09 UTC, truonghungit commented
This email is not valid, please check the email validator
![image](https://user-images.githubusercontent.com/9523581/127279488-a480d19b-7f2b-43ce-b69f-0a531dbe0913.png)

2021-07-28 08:41 UTC, dtngoc99 commented
Update demo: 

https://loom.com/share/dde4e4aadcee49eab8c9a7cdd6c40c18

2021-07-28 11:07 UTC, luantc13 approved these changes
Great work!
No major issues, happy to merge.

2021-07-28 11:07 UTC, luantc13 commented on src/contacts/components/ContactForm.vue
> +      roleRules: [validators.requiredKey("Role is required")],
I don't think `requiredKey` is a good name.

2021-07-29 02:18 UTC, truonghungit requested changes

2021-07-29 02:18 UTC, truonghungit commented on src/shared/actions/actions.js
> +};
It seems a utility function, not a action, I  think it can't help you anything

2021-07-29 02:18 UTC, truonghungit commented on src/contacts/components/ContactForm.vue
> +            <div class="d-flex w-600">
this element will not responsive on mobile

2021-07-29 02:18 UTC, truonghungit commented on src/contacts/components/ContactForm.vue
> +            <div class="w-50per">
you can use the v-row -> v-col in this case

2021-07-29 02:18 UTC, truonghungit commented on src/contacts/components/ContactForm.vue
> +            <div class="w-50per">
![image](https://user-images.githubusercontent.com/9523581/127420870-a8efcf03-a5f0-4628-a6db-5ec95e4da13b.png)

2021-07-29 02:18 UTC, truonghungit commented on src/contacts/components/ContactForm.vue
> +        }}</v-btn>
We should disable the submit button while request API to prevent users click more
![image](https://user-images.githubusercontent.com/9523581/127421035-1f102899-c642-4bd7-bf07-e400192c95bc.png)

2021-07-29 06:02 UTC, dtngoc99 commented
Update demo:

https://loom.com/share/df08ecd3bd9f463e9a569d32c4be4cc6

2021-07-29 08:42 UTC, truonghungit approved these changes

2021-07-29 08:46 UTC, merged